# Generated by Django 5.0.3 on 2024-03-11 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[("Children's", "Children's"), ('Fantasy', 'Fantasy'), ('Sci-Fi', 'Sci-Fi'), ('Adventure', 'Adventure'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Satire', 'Satire'), ('Utopia', 'Utopia')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90, unique=True)),
                ('book_image', models.URLField(blank=True, null=True)),
                ('year_published', models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(1999)])),
                ('description', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('book_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.author')),
                ('genre', models.ManyToManyField(to='books.bookgenre')),
            ],
        ),
        migrations.CreateModel(
            name='BookReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Have Already Read', 'Have Already Read'), ('Currently Reading', 'Currently Reading'), ('Want To Read', 'Want To Read')], max_length=30, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('book', 'user')},
            },
        ),
    ]
