# Generated by Django 5.0.3 on 2024-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_books',
            field=models.ManyToManyField(to='books.book'),
        ),
    ]
